import {products, STORE} from './data/products.js';
import {demoReviews} from './data/reviews-demo.js';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const money=n=>n==null?'Price pending':new Intl.NumberFormat('en-US',{style:'currency',currency:STORE.currency}).format(n);
const productBy=id=>products.find(p=>p.id==id);
let cart=JSON.parse(localStorage.getItem('pawelier-cart')||'{}'), activeImage=0, touchX=0;
const grid=$('#productGrid');

function productHref(p){return `#/product/${p.slug}`}
function card(p){return `<article class="product-card reveal" data-category="${p.category}"><a class="card-link" href="${productHref(p)}" aria-label="View ${p.name}"><span class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:''}</span><span class="product-info"><span class="meta"><span>${p.category}</span></span><strong>${p.name}</strong><span class="card-description">${p.description}</span><span class="price-row"><b>${money(p.price)}</b><u>View details</u></span></span></a><button class="quick add" data-id="${p.id}" aria-label="Add ${p.name} to bag"><span>Add to bag</span> +</button></article>`}
function render(filter='All'){grid.innerHTML=products.filter(p=>filter==='All'||p.category===filter).map(card).join('');observe()}
function add(id,qty=1,open=true){cart[id]=(cart[id]||0)+qty;save();if(open)openCart();toast(qty>1?`${qty} items added to your bag`:'Added to your bag')}
function save(){localStorage.setItem('pawelier-cart',JSON.stringify(cart));renderCart()}
function renderCart(){
  for(const id of Object.keys(cart)) if(!productBy(id)) delete cart[id];
  const entries=Object.entries(cart).filter(([,q])=>q>0), priced=entries.every(([id])=>productBy(id)?.price!=null);
  const total=priced?entries.reduce((sum,[id,q])=>sum+productBy(id).price*q,0):0;
  $('#cartCount').textContent=entries.reduce((sum,[,q])=>sum+q,0);
  $('#cartItems').innerHTML=entries.map(([id,q])=>{const p=productBy(id);return `<div class="cart-item"><a href="${productHref(p)}"><img src="${p.image}" alt="${p.name}"></a><div><a href="${productHref(p)}"><h4>${p.name}</h4></a><div class="qty"><button data-change="-1" data-id="${id}" aria-label="Decrease quantity">−</button><span>${q}</span><button data-change="1" data-id="${id}" aria-label="Increase quantity">+</button></div></div><div><b>${money(p.price)}</b><button class="remove" data-id="${id}">Remove</button></div></div>`}).join('');
  $('#subtotal').textContent=entries.length&&!priced?'Pending':money(total);
  $('#shippingText').textContent=entries.length&&!priced?'Shipping is calculated after pricing is confirmed.':total>=STORE.freeShipping?'Complimentary shipping unlocked.':`You're ${money(STORE.freeShipping-total)} away from complimentary shipping.`;
  $('#shippingBar').style.width=`${priced?Math.min(100,total/STORE.freeShipping*100):0}%`;
  $('.cart-drawer').classList.toggle('empty',!entries.length);
}
function openCart(){$('.overlay').hidden=false;requestAnimationFrame(()=>$('.cart-drawer').classList.add('open'));$('.cart-drawer').setAttribute('aria-hidden','false')}
function closeCart(){$('.cart-drawer').classList.remove('open');$('.cart-drawer').setAttribute('aria-hidden','true');setTimeout(()=>$('.overlay').hidden=true,400)}
function toast(t){$('.toast').textContent=t;$('.toast').classList.add('show');setTimeout(()=>$('.toast').classList.remove('show'),1800)}
function setGallery(p,index){activeImage=(index+p.images.length)%p.images.length;const img=$('.gallery-main img');if(!img)return;img.classList.add('changing');setTimeout(()=>{img.src=p.images[activeImage];img.alt=`${p.name}, view ${activeImage+1}`;img.classList.remove('changing')},120);$$('.gallery-thumb').forEach((b,i)=>{b.classList.toggle('active',i===activeImage);b.setAttribute('aria-current',i===activeImage)})}
function videos(p){if(!p.videos?.length)return `<p class="empty-media">No product video has been published yet. We never use static images to imitate playable video.</p>`;return `<div class="video-grid">${p.videos.map(v=>v.type==='mp4'?`<video controls preload="metadata"><source src="${v.url}" type="video/mp4">Your browser cannot play this video.</video>`:`<a class="video-card" href="${v.url}" target="_blank" rel="noopener"><span>▶</span><b>Watch on ${v.type}</b><small>Opens the original, official post</small></a>`).join('')}</div>`}
function renderProduct(p){
  const related=products.filter(x=>x.id!==p.id);
  const source=p.sourceUrl?`<a class="btn dark" href="${p.sourceUrl}" target="_blank" rel="noopener noreferrer">View supplied listing <span>↗</span></a>`:`<button class="btn dark" disabled>Product link required</button>`;
  $('#productView').innerHTML=`<div class="product-shell"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="#top">Home</a><span>→</span><a href="#shop">Current collection</a><span>→</span><span>${p.name}</span></nav><div class="product-hero"><div class="gallery"><button class="gallery-main" data-lightbox aria-label="Enlarge current image"><img src="${p.images[0]}" alt="${p.name}"></button><button class="gallery-arrow prev" data-gallery="-1" aria-label="Previous image">←</button><button class="gallery-arrow next" data-gallery="1" aria-label="Next image">→</button><div class="gallery-thumbs">${p.images.map((src,i)=>`<button class="gallery-thumb ${i?'':'active'}" data-gallery-index="${i}" aria-label="Show image ${i+1}"><img src="${src}" alt=""></button>`).join('')}</div></div><div class="buy-panel"><p class="eyebrow">Current collection</p><h1>${p.name}</h1><h2>${money(p.price)}</h2><p class="product-lede">${p.description}</p><p class="empty-media">This listing intentionally contains no unverified name, price, specifications or product claims.</p><label class="option-label">Quantity<span class="page-qty"><button data-page-qty="-1" aria-label="Decrease quantity">−</button><output id="pageQty">1</output><button data-page-qty="1" aria-label="Increase quantity">+</button></span></label><div class="product-actions"><button class="btn buy page-add" data-id="${p.id}">Add to bag</button>${source}</div><div class="assurances"><span>✓ <b>Transparent</b><small>No invented details</small></span><span>◌ <b>Focused</b><small>One of two products</small></span><span>⌁ <b>Source-led</b><small>Details stay verifiable</small></span></div></div></div><div class="product-sections"><section><p class="eyebrow">The details</p><h2>Information pending verification.</h2><p>${p.sourceUrl?'Use the supplied source listing above for the latest seller-provided details.':'The original link for this product was not available, and no matching verified data was found in the project.'}</p></section><section><p class="eyebrow">Product gallery</p><h2>Placeholders, clearly labelled.</h2><div class="detail-images">${p.images.map((x,i)=>`<button data-detail-image="${i}" aria-label="Enlarge placeholder ${i+1}"><img src="${x}" alt="${p.name}: verified image not supplied" loading="lazy"></button>`).join('')}</div></section><section><p class="eyebrow">The other selection</p><h2>Complete the two-product edit.</h2><div class="related-grid">${related.map(card).join('')}</div></section></div></div>`;
  activeImage=0; observe();
}
function route(){const match=location.hash.match(/^#\/product\/([^/]+)/);const p=match&&products.find(x=>x.slug===match[1]);$('#homeView').hidden=!!p;$('#productView').hidden=!p;document.body.classList.toggle('on-product',!!p);if(p){renderProduct(p);scrollTo(0,0);document.title=`${p.name} — Pawelier`}else document.title='Pawelier — A focused two-product collection'}

let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});function observe(){$$('.reveal:not(.visible)').forEach(e=>io.observe(e))}
render();renderCart();$('#reviews').innerHTML=demoReviews.map(r=>`<article class="review reveal"><span class="stars">★★★★★</span><blockquote>“${r.text}”</blockquote><footer><i class="avatar">${r.initials}</i><span><b>${r.name}</b><small>Demo note · ${r.product}</small></span></footer></article>`).join('');$('#moments').innerHTML=products.slice(-3).map(p=>`<a class="ugc-card reveal" href="${productHref(p)}"><img src="${p.detail}" alt="${p.name} in use" loading="lazy"><div><small>PRODUCT MOMENT</small><b>${p.name}</b><span>Explore →</span></div></a>`).join('');observe();route();
document.addEventListener('click',e=>{const addBtn=e.target.closest('.add');if(addBtn){e.preventDefault();e.stopPropagation();add(+addBtn.dataset.id)}const f=e.target.closest('[data-filter]');if(f){$$('[data-filter]').forEach(x=>x.classList.remove('active'));f.classList.add('active');render(f.dataset.filter)}const ch=e.target.closest('[data-change]');if(ch){cart[ch.dataset.id]=Math.max(0,(cart[ch.dataset.id]||0)+ +ch.dataset.change);save()}const rem=e.target.closest('.remove');if(rem){delete cart[rem.dataset.id];save()}const g=e.target.closest('[data-gallery]');if(g)setGallery(productBySlug(),activeImage+ +g.dataset.gallery);const gi=e.target.closest('[data-gallery-index]');if(gi)setGallery(productBySlug(),+gi.dataset.galleryIndex);const pq=e.target.closest('[data-page-qty]');if(pq)$('#pageQty').value=Math.max(1,+$('#pageQty').value+ +pq.dataset.pageQty);const sq=e.target.closest('[data-set-qty]');if(sq)$('#pageQty').value=sq.dataset.setQty;const pa=e.target.closest('.page-add');if(pa)add(+pa.dataset.id,+$('#pageQty').value);const pb=e.target.closest('.page-buy');if(pb){add(+pb.dataset.id,+$('#pageQty').value);toast('Ready for secure checkout')}const bundle=e.target.closest('.bundle-add');if(bundle){bundle.dataset.ids.split(',').forEach(id=>add(+id,1,false));openCart();toast('Set added — 10% offer noted')}const lb=e.target.closest('[data-lightbox]');if(lb)openLightbox($('.gallery-main img').src,$('.gallery-main img').alt);const di=e.target.closest('[data-detail-image]');if(di){const p=productBySlug();openLightbox(p.images[+di.dataset.detailImage],p.name)}const cat=e.target.closest('[data-category-link]');if(cat){render(cat.dataset.category);setTimeout(()=>$('#shop').scrollIntoView(),0)}});
function productBySlug(){return products.find(p=>location.hash.includes(p.slug))}
function openLightbox(src,alt){$('#lightboxImage').src=src;$('#lightboxImage').alt=alt;$('#lightbox').showModal()}
window.addEventListener('hashchange',()=>{closeCart();route()});$('.cart-btn').onclick=openCart;$('.drawer-close').onclick=closeCart;$('.overlay').onclick=closeCart;$('.close-cart').onclick=closeCart;$('#lightbox .modal-close').onclick=()=>$('#lightbox').close();$('#searchDialog .modal-close').onclick=()=>$('#searchDialog').close();$('.search').onclick=()=>{$('#searchDialog').showModal();$('#searchInput').focus()};$('.account').onclick=()=>toast('Account sign-in is coming soon');$('.checkout').onclick=()=>toast(Object.keys(cart).some(id=>cart[id]>0&&productBy(id)?.price==null)?'Checkout unavailable until pricing is confirmed':'Checkout demo — no payment will be taken');$('.menu-btn').onclick=()=>{$('.mobile-menu').classList.add('open');$('.mobile-menu').setAttribute('aria-hidden','false')};$('.menu-close').onclick=()=>$('.mobile-menu').classList.remove('open');$$('.mobile-menu a').forEach(a=>a.onclick=()=>$('.mobile-menu').classList.remove('open'));
$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase().trim();$('#searchResults').innerHTML=q?products.filter(p=>(p.name+p.category+p.description).toLowerCase().includes(q)).map(p=>`<a href="${productHref(p)}" onclick="this.closest('dialog').close()"><img src="${p.image}" alt=""><span><b>${p.name}</b><small>${money(p.price)}</small></span></a>`).join('')||'<p>No essentials found.</p>':''};$('#searchForm').onsubmit=e=>e.preventDefault();
window.addEventListener('scroll',()=>$('#header').classList.toggle('scrolled',scrollY>80),{passive:true});$('#newsletter').onsubmit=e=>{e.preventDefault();$('#formNote').textContent='Welcome to the good-pet list.';e.target.reset()};
document.addEventListener('touchstart',e=>{if(e.target.closest('.gallery-main'))touchX=e.changedTouches[0].clientX},{passive:true});document.addEventListener('touchend',e=>{if(!e.target.closest('.gallery-main'))return;const d=e.changedTouches[0].clientX-touchX,p=productBySlug();if(p&&Math.abs(d)>45)setGallery(p,activeImage+(d<0?1:-1))},{passive:true});
