import {products, STORE} from './data/products.js';
import {demoReviews} from './data/reviews-demo.js';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:STORE.currency}).format(n);
let cart=JSON.parse(localStorage.getItem('pawelier-cart')||'{}');
const grid=$('#productGrid');
function card(p){return `<article class="product-card reveal" data-category="${p.category}"><button class="product-image details" data-id="${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:''}</button><button class="quick add" data-id="${p.id}">Quick add +</button><div class="product-info"><div class="meta"><span>${p.category}</span><span class="rating">★ ${p.rating} (${p.reviews})</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="price-row"><b>${money(p.price)}</b><button class="view details" data-id="${p.id}">View details</button></div></div></article>`}
function render(filter='All'){grid.innerHTML=products.filter(p=>filter==='All'||p.category===filter).map(card).join(''); observe();}
function add(id){cart[id]=(cart[id]||0)+1;save();openCart();toast('Added to your bag');}
function save(){localStorage.setItem('pawelier-cart',JSON.stringify(cart));renderCart()}
function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0);const total=entries.reduce((s,[id,q])=>s+products.find(p=>p.id==id).price*q,0);$('#cartCount').textContent=entries.reduce((s,[,q])=>s+q,0);$('#cartItems').innerHTML=entries.map(([id,q])=>{const p=products.find(x=>x.id==id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><div class="qty"><button data-change="-1" data-id="${id}" aria-label="Decrease quantity">−</button><span>${q}</span><button data-change="1" data-id="${id}" aria-label="Increase quantity">+</button></div></div><div><b>${money(p.price*q)}</b><button class="remove" data-id="${id}">Remove</button></div></div>`}).join('');$('#subtotal').textContent=money(total);const remain=Math.max(0,STORE.freeShipping-total);$('#shippingText').textContent=remain?`You're ${money(remain)} away from complimentary shipping.`:'Complimentary shipping unlocked.';$('#shippingBar').style.width=`${Math.min(100,total/STORE.freeShipping*100)}%`;$('.cart-drawer').classList.toggle('empty',!entries.length)}
function openCart(){$('.overlay').hidden=false;requestAnimationFrame(()=>$('.cart-drawer').classList.add('open'));$('.cart-drawer').setAttribute('aria-hidden','false')}
function closeCart(){$('.cart-drawer').classList.remove('open');$('.cart-drawer').setAttribute('aria-hidden','true');setTimeout(()=>$('.overlay').hidden=true,400)}
function modal(id){const p=products.find(x=>x.id==id);$('#modalContent').innerHTML=`<div class="modal-grid"><div class="modal-gallery"><img class="modal-main" src="${p.image}" alt="${p.name}"><div class="thumbs"><button data-src="${p.image}"><img src="${p.image}" alt="Front view"></button><button data-src="${p.detail}"><img src="${p.detail}" alt="${p.name} in use"></button></div></div><div class="modal-copy"><p class="eyebrow">${p.category} / everyday essential</p><span class="rating">★★★★★ &nbsp; ${p.rating} preview rating</span><h2>${p.name}</h2><h3>${money(p.price)}</h3><p class="desc">${p.description}</p><ul>${p.benefits.map(x=>`<li>✓ &nbsp; ${x}</li>`).join('')}</ul><details><summary>How it works</summary><p class="desc">Designed for intuitive, everyday use. Follow the care instructions supplied with your order.</p></details><div class="modal-actions"><button class="btn dark add" data-id="${p.id}">Add to bag</button><button class="btn buy add" data-id="${p.id}">Buy now</button></div></div></div>`;$('#productModal').showModal()}
function toast(t){$('.toast').textContent=t;$('.toast').classList.add('show');setTimeout(()=>$('.toast').classList.remove('show'),1800)}
let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});function observe(){$$('.reveal:not(.visible)').forEach(e=>io.observe(e))}
render();renderCart();$('#reviews').innerHTML=demoReviews.map(r=>`<article class="review reveal"><span class="stars">★★★★★</span><blockquote>“${r.text}”</blockquote><footer><i class="avatar">${r.initials}</i><span><b>${r.name}</b><small>Demo note · ${r.product}</small></span></footer></article>`).join('');observe();
document.addEventListener('click',e=>{const addBtn=e.target.closest('.add');if(addBtn)add(+addBtn.dataset.id);const d=e.target.closest('.details');if(d)modal(+d.dataset.id);const f=e.target.closest('[data-filter]');if(f){$$('[data-filter]').forEach(x=>x.classList.remove('active'));f.classList.add('active');render(f.dataset.filter);$('#shop').scrollIntoView()}const ch=e.target.closest('[data-change]');if(ch){cart[ch.dataset.id]=Math.max(0,(cart[ch.dataset.id]||0)+ +ch.dataset.change);save()}const rem=e.target.closest('.remove');if(rem){delete cart[rem.dataset.id];save()}const th=e.target.closest('[data-src]');if(th)$('.modal-main').src=th.dataset.src});
$('.cart-btn').onclick=openCart;$('.drawer-close').onclick=closeCart;$('.overlay').onclick=closeCart;$('.close-cart').onclick=closeCart;$('.modal-close').onclick=()=>$('#productModal').close();$('.menu-btn').onclick=()=>{$('.mobile-menu').classList.add('open');$('.mobile-menu').setAttribute('aria-hidden','false')};$('.menu-close').onclick=()=>$('.mobile-menu').classList.remove('open');$$('.mobile-menu a').forEach(a=>a.onclick=()=>$('.mobile-menu').classList.remove('open'));
window.addEventListener('scroll',()=>$('#header').classList.toggle('scrolled',scrollY>80),{passive:true});
$('#newsletter').onsubmit=e=>{e.preventDefault();$('#formNote').textContent='Welcome to the good-pet list.';e.target.reset()};
$$('.magnetic').forEach(b=>{b.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});b.addEventListener('pointerleave',()=>b.style.transform='')});
